--- #YAML:1.0
name:               Config-Scoped
version:            0.13
abstract:           feature rich configuration file parser
author:
    - Karl Gaissmaier <karl.gaissmaier at uni-ulm.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:               0
    Digest::MD5:        0
    Error:              0
    File::Basename:     0
    File::Spec:         0
    Parse::RecDescent:  1.94
    Safe:               0
    Storable:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
